service: build-pelican-in-lambda

plugins:
- serverless-python-requirements
custom:
  stage: "${opt:stage, env:SLS_STAGE, 'dev'}"
  log_level: "${env:LOG_LEVEL, 'INFO'}"

  pythonRequirements:
    dockerizePip: false


provider:
  name: aws
  runtime: python3.6
  stage: ${self:custom.stage}
  environment:
    LOG_LEVEL: ${self:custom.log_level}
  stackTags:
    x-service: build-pelican-in-lambda
    x-stack: ${self:service}-${self:provider.stage}
  region: eu-central-1
  iamRoleStatements:
  - Effect: Allow
    Action:
    - lambda:InvokeFunction
    Resource: "*"
  - Effect: Allow
    Action:
    - "s3:PutObject"
    Resource:
      Fn::Join: ['', [Fn::GetAtt: [ BlogBucket, Arn ], '/*'] ]


functions:
  async_rebuild_blog_from_git:
    handler: handlers/action.async_handler
    description: "Rebuilds pelican blog from contents stored in git"
    memorySize: 512
    timeout: 600
  rebuild_blog_from_git:
    handler: handlers/action.http_rebuild_blog
    description: "Makes async call to async_rebuild_blog_from_git lambda"
    events:
    - http:
        path: rebuild
        method: get


resources:
  Resources:
    BlogBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: "chrabasz.cz"